
version: 2.1
    jobs:
      - welcome/run
      build: 
        docker:
          - image: circleci/node:8.9.0

          steps:
            - checkout
            - run: npm install
            - run: npm test
